version: '3.0'

services:
  fastapi:
    build: ./FGT
    container_name: fastapi
    restart: unless-stopped
    volumes:
      - ./FGT/secrets.py:/app/secrets.py
    ports:
      - 8000:8000
    networks:
      - test-network

  react-web:
    build: ./react-app
    restart: unless-stopped
    container_name: react-web
    ports:
      - 5000:5000
    networks:
      - test-network
    volumes:
      - ./react-app/.env:/app/.env
    depends_on:
      - fastapi

networks:
  test-network:
