version: '3.0'

services:
  fastapi:
    build: ./FGT
    container_name: fastapi
    restart: unless-stopped
    volumes:
      - ./FGT/secrets.py:/app/secrets.py
    ports:
      - 8000:8000

  react-web:
    build: ./react-app
    restart: unless-stopped
    container_name: nginx-react-web
    ports:
      - 1810:1810
    depends_on:
      - fastapi

